### ISSUE TITLE
3gpp docker container isn't listening for NETCONF

### ISSUE THREAD

**Issue by natifridman** [clicon/clixon-examples#1]
Hi,

I'm checking the 3gpp docker container and it looks like that it's listening only for RESTCONF.
Is there any way to enable NETCONF too? I'm able to use the clixon_netconf, but I want to use it from outside the container.

I couldn't join the Slack channel so I'm trying here...
Thanks!

**Comment by olofhagsand** [comment]
You should be able to use the slack invite that is currently in the README, or try this: https://join.slack.com/t/clixondev/shared_invite/zt-o8lv7ysk-vcLb7yY9S7XMEklqqVBziQ

Netconf is not a process itself, it is invoked as a client command, I tried the container and followed the README to try out netconf as follows:
```
olof@alarik> make docker
...
olof@alarik> sudo docker run --rm -p 8081:80 --name 3gpp -d clixon/3gpp
832dcc5505577828664511350e49941d46855e26ad15651d0d53b84dea5d7e7f
olof@alarik> sudo docker exec -it 3gpp clixon_netconf
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="42"><capabilities><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability></capabilities><session-id>2</session-id></hello>]]>]]>
```

For more info, see https://github.com/clicon/clixon/blob/master/docker/main/README.md where the container used to build as a template for the 3gpp container is described.
Further, this 3gpp container is an example and should probably need some more work to make usable. Also, the 3gpp spec has not been updated in some time, there are newer 3GPP standards published.

**Comment by natifridman** [comment]
Thanks for the info! I asked my other questions in the slack channel
